package com.ryang.bf.bfjczs;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import org.junit.Test;

/**
 * @Auther: renyang
 * @Date: 2019/5/6 20:47
 * @Description:
 */
public class Case68_4Test {

    String s = "{\n" +
            "    \"resultCode\": \"000000\",\n" +
            "    \"resultMsg\": \"\",\n" +
            "    \"resultObj\": {\n" +
            "        \"sbxmlist\": [\n" +
            "            {\n" +
            "                \"sbxmdm\": \"xqycwbb\",\n" +
            "                \"sbxmmc\": \"财务报表2013(小企业会计准则)\",\n" +
            "                \"ljdz\": \"/zjgfzjdzswjsbweb/pages/sb/nssb/bdlb.html\",\n" +
            "                \"pzxh\": \"1218487171901\",\n" +
            "                \"sssq_q\": \"2019-04-01\",\n" +
            "                \"sssq_z\": \"2019-04-30\",\n" +
            "                \"sbjzrq\": \"\",\n" +
            "                \"sbzt\": \"已申报\",\n" +
            "                \"sbrq\": \"2019-05-08\",\n" +
            "                \"kkzt\": \"\",\n" +
            "                \"kkrq\": \"\",\n" +
            "                \"drxx\": \"已导入\",\n" +
            "                \"qztj\": \"\",\n" +
            "                \"tsxx\": \"\",\n" +
            "                \"pzzl_dm\": \"901\",\n" +
            "                \"zsxm_dm\": \"99990\",\n" +
            "                \"nsrdzdah\": \"10213300000000006945\",\n" +
            "                \"sfdr\": \"Y\",\n" +
            "                \"sfkk\": \"N\",\n" +
            "                \"yzpzzl_dm\": \"ZL1001003\",\n" +
            "                \"nsqx_dm\": \"06\",\n" +
            "                \"sbzk\": \"1\",\n" +
            "                \"fwdz\": \"/zjgfzjdzswjsbweb/\",\n" +
            "                \"bjtp\": \"pages/sb/sbxm/tpsm/cwbb_xqy.jpg\",\n" +
            "                \"tbsm\": \"pages/sb/sbxm/tbsm/bxcwbb_sm.html\",\n" +
            "                \"fzsh\": \"N\",\n" +
            "                \"qsbdz\": \"pages/sb/cwbb/xqycwbb/qsb.html\",\n" +
            "                \"qylx\": \"\",\n" +
            "                \"drzt\": \"1\",\n" +
            "                \"cbsb\": \"0\",\n" +
            "                \"gzsb\": \"0\",\n" +
            "                \"yqsb\": \"0\",\n" +
            "                \"yqbz\": \"\",\n" +
            "                \"xmzslx\": \"\",\n" +
            "                \"kkbz\": \"0\",\n" +
            "                \"acsb\": \"N\",\n" +
            "                \"sfqz\": \"N\",\n" +
            "                \"yqwzpd\": \"N\",\n" +
            "                \"plxh\": \"-10\",\n" +
            "                \"dr_msg\": \"\",\n" +
            "                \"jcywbz\": \"\",\n" +
            "                \"wjxzdz\": \"https://zjgs-oss-01-dzswjappcenter.oss-cn-hangzhou.aliyuncs.com/wssbdownload/%E8%B4%A2%E5%8A%A1%E6%8A%A5%E8%A1%A82013%28%E5%B0%8F%E4%BC%81%E4%B8%9A%E4%BC%9A%E8%AE%A1%E5%87%86%E5%88%99%29.xlsx\",\n" +
            "                \"wjdrbz\": \"\",\n" +
            "                \"gdslx\": \"1\",\n" +
            "                \"lsbbz\": \"N\",\n" +
            "                \"lsbdz\": \"/zjgfzjdzswjsbweb/\",\n" +
            "                \"wcjybh\": \"\",\n" +
            "                \"sfxz\": \"Y\",\n" +
            "                \"wsid\": \"\",\n" +
            "                \"sfsqjy\": \"\",\n" +
            "                \"jsdrbz\": \"\",\n" +
            "                \"sfcjl\": \"\",\n" +
            "                \"cjxmmc\": \"\",\n" +
            "                \"ztxmbz\": \"Y\",\n" +
            "                \"dbrwbz\": \"Y\",\n" +
            "                \"yykkbz\": \"N\",\n" +
            "                \"ztpzxh\": \"\",\n" +
            "                \"yqts\": \"\",\n" +
            "                \"zcbz\": \"N\",\n" +
            "                \"ylbz\": \"\",\n" +
            "                \"bszndz\": \"\",\n" +
            "                \"czgcdz\": \"https://etax.zjtax.gov.cn/SignCheck/czgc/xqycwbb.htm\",\n" +
            "                \"blzybz\": \"Y\",\n" +
            "                \"zfwdz\": \"\",\n" +
            "                \"sfdqbb\": \"Y\",\n" +
            "                \"sfzxqbb\": \"Y\",\n" +
            "                \"hsqjbz\": \"\",\n" +
            "                \"sfjscj\": \"\",\n" +
            "                \"sfjsdr\": \"\",\n" +
            "                \"pbbtn\": \"\"\n" +
            "            },\n" +
            "            {\n" +
            "                \"sbxmdm\": \"zzsybnsr\",\n" +
            "                \"sbxmmc\": \"增值税一般纳税人申报\",\n" +
            "                \"ljdz\": \"/zjgfctais2/wssb/ybnsr2012/zzs_wqx.jsp\",\n" +
            "                \"pzxh\": \"1218487170105\",\n" +
            "                \"sssq_q\": \"2019-04-01\",\n" +
            "                \"sssq_z\": \"2019-04-30\",\n" +
            "                \"sbjzrq\": \"2019-05-21\",\n" +
            "                \"sbzt\": \"已申报\",\n" +
            "                \"sbrq\": \"2019-05-13\",\n" +
            "                \"kkzt\": \"未扣款\",\n" +
            "                \"kkrq\": \"\",\n" +
            "                \"drxx\": \"已导入\",\n" +
            "                \"qztj\": \"\",\n" +
            "                \"tsxx\": \"\",\n" +
            "                \"pzzl_dm\": \"105\",\n" +
            "                \"zsxm_dm\": \"10101\",\n" +
            "                \"nsrdzdah\": \"10213300000000006945\",\n" +
            "                \"sfdr\": \"Y\",\n" +
            "                \"sfkk\": \"Y\",\n" +
            "                \"yzpzzl_dm\": \"\",\n" +
            "                \"nsqx_dm\": \"\",\n" +
            "                \"sbzk\": \"1\",\n" +
            "                \"fwdz\": \"/zjgfctais2/wssb/\",\n" +
            "                \"bjtp\": \"\",\n" +
            "                \"tbsm\": \"\",\n" +
            "                \"fzsh\": \"Y\",\n" +
            "                \"qsbdz\": \"\",\n" +
            "                \"qylx\": \"\",\n" +
            "                \"drzt\": \"\",\n" +
            "                \"cbsb\": \"0\",\n" +
            "                \"gzsb\": \"0\",\n" +
            "                \"yqsb\": \"0\",\n" +
            "                \"yqbz\": \"0\",\n" +
            "                \"xmzslx\": \"\",\n" +
            "                \"kkbz\": \"0\",\n" +
            "                \"acsb\": \"N\",\n" +
            "                \"sfqz\": \"N\",\n" +
            "                \"yqwzpd\": \"Y\",\n" +
            "                \"plxh\": \"-9\",\n" +
            "                \"dr_msg\": \"\",\n" +
            "                \"jcywbz\": \"\",\n" +
            "                \"wjxzdz\": \"\",\n" +
            "                \"wjdrbz\": \"\",\n" +
            "                \"gdslx\": \"1\",\n" +
            "                \"lsbbz\": \"N\",\n" +
            "                \"lsbdz\": \"/zjgfctais2/wssb/\",\n" +
            "                \"wcjybh\": \"\",\n" +
            "                \"sfxz\": \"Y\",\n" +
            "                \"wsid\": \"\",\n" +
            "                \"sfsqjy\": \"\",\n" +
            "                \"jsdrbz\": \"\",\n" +
            "                \"sfcjl\": \"\",\n" +
            "                \"cjxmmc\": \"\",\n" +
            "                \"ztxmbz\": \"Y\",\n" +
            "                \"dbrwbz\": \"Y\",\n" +
            "                \"yykkbz\": \"Y\",\n" +
            "                \"ztpzxh\": \"\",\n" +
            "                \"yqts\": \"\",\n" +
            "                \"zcbz\": \"\",\n" +
            "                \"ylbz\": \"\",\n" +
            "                \"bszndz\": \"http://www.zjzwfw.gov.cn/art/2018/7/9/art_49039_31016.html\",\n" +
            "                \"czgcdz\": \"https://etax.zjtax.gov.cn/SignCheck/czgc/zzsybnsr.htm\",\n" +
            "                \"blzybz\": \"Y\",\n" +
            "                \"zfwdz\": \"\",\n" +
            "                \"sfdqbb\": \"Y\",\n" +
            "                \"sfzxqbb\": \"Y\",\n" +
            "                \"hsqjbz\": \"\",\n" +
            "                \"sfjscj\": \"\",\n" +
            "                \"sfjsdr\": \"\",\n" +
            "                \"pbbtn\": \"\"\n" +
            "            },\n" +
            "            {\n" +
            "                \"sbxmdm\": \"fjsf\",\n" +
            "                \"sbxmmc\": \"城建税、教育费附加、地方教育附加税（费）申报表\",\n" +
            "                \"ljdz\": \"/zjgfzjdzswjsbweb/pages/sb/nssb/bdlb.html\",\n" +
            "                \"pzxh\": \"1218487172851\",\n" +
            "                \"sssq_q\": \"2019-04-01\",\n" +
            "                \"sssq_z\": \"2019-04-30\",\n" +
            "                \"sbjzrq\": \"2019-05-21\",\n" +
            "                \"sbzt\": \"未申报\",\n" +
            "                \"sbrq\": \"\",\n" +
            "                \"kkzt\": \"未扣款\",\n" +
            "                \"kkrq\": \"\",\n" +
            "                \"drxx\": \"未导入\",\n" +
            "                \"qztj\": \"\",\n" +
            "                \"tsxx\": \"\",\n" +
            "                \"pzzl_dm\": \"851\",\n" +
            "                \"zsxm_dm\": \"99985\",\n" +
            "                \"nsrdzdah\": \"10213300000000006945\",\n" +
            "                \"sfdr\": \"Y\",\n" +
            "                \"sfkk\": \"Y\",\n" +
            "                \"yzpzzl_dm\": \"BDA0610678\",\n" +
            "                \"nsqx_dm\": \"06\",\n" +
            "                \"sbzk\": \"0\",\n" +
            "                \"fwdz\": \"/zjgfzjdzswjsbweb/\",\n" +
            "                \"bjtp\": \"pages/sb/sbxm/tpsm/fjsf.jpg\",\n" +
            "                \"tbsm\": \"pages/sb/sbxm/tbsm/fjsf_sm.html\",\n" +
            "                \"fzsh\": \"N\",\n" +
            "                \"qsbdz\": \"pages/sb/dsbb/fjssbb/qsb.html\",\n" +
            "                \"qylx\": \"\",\n" +
            "                \"drzt\": \"0\",\n" +
            "                \"cbsb\": \"0\",\n" +
            "                \"gzsb\": \"0\",\n" +
            "                \"yqsb\": \"0\",\n" +
            "                \"yqbz\": \"0\",\n" +
            "                \"xmzslx\": \"\",\n" +
            "                \"kkbz\": \"0\",\n" +
            "                \"acsb\": \"N\",\n" +
            "                \"sfqz\": \"N\",\n" +
            "                \"yqwzpd\": \"N\",\n" +
            "                \"plxh\": \"-7\",\n" +
            "                \"dr_msg\": \"\",\n" +
            "                \"jcywbz\": \"\",\n" +
            "                \"wjxzdz\": \"https://zjgs-oss-01-dzswjappcenter.oss-cn-hangzhou.aliyuncs.com/wssbdownload/%E5%9F%8E%E5%BB%BA%E7%A8%8E%E3%80%81%E6%95%99%E8%82%B2%E8%B4%B9%E9%99%84%E5%8A%A0%E3%80%81%E5%9C%B0%E6%96%B9%E6%95%99%E8%82%B2%E9%99%84%E5%8A%A0%E7%A8%8E%EF%BC%88%E8%B4%B9%EF%BC%89%E7%94%B3%E6%8A%A5%E8%A1%A8.xlsx\",\n" +
            "                \"wjdrbz\": \"\",\n" +
            "                \"gdslx\": \"2\",\n" +
            "                \"lsbbz\": \"Y\",\n" +
            "                \"lsbdz\": \"/zjgfzjdzswjsbweb/fjsf/sb_fjsf_cjjyfj/Do0SbtjSbb.do\",\n" +
            "                \"wcjybh\": \"\",\n" +
            "                \"sfxz\": \"N\",\n" +
            "                \"wsid\": \"\",\n" +
            "                \"sfsqjy\": \"\",\n" +
            "                \"jsdrbz\": \"\",\n" +
            "                \"sfcjl\": \"\",\n" +
            "                \"cjxmmc\": \"\",\n" +
            "                \"ztxmbz\": \"Y\",\n" +
            "                \"dbrwbz\": \"Y\",\n" +
            "                \"yykkbz\": \"Y\",\n" +
            "                \"ztpzxh\": \"\",\n" +
            "                \"yqts\": \"\",\n" +
            "                \"zcbz\": \"N\",\n" +
            "                \"ylbz\": \"\",\n" +
            "                \"bszndz\": \"http://www.zjzwfw.gov.cn/art/2017/11/10/art_49039_30364.html\",\n" +
            "                \"czgcdz\": \"https://etax.zjtax.gov.cn/SignCheck/czgc/fjsf.htm\",\n" +
            "                \"blzybz\": \"Y\",\n" +
            "                \"zfwdz\": \"\",\n" +
            "                \"sfdqbb\": \"Y\",\n" +
            "                \"sfzxqbb\": \"Y\",\n" +
            "                \"hsqjbz\": \"\",\n" +
            "                \"sfjscj\": \"\",\n" +
            "                \"sfjsdr\": \"\",\n" +
            "                \"pbbtn\": \"\"\n" +
            "            },\n" +
            "            {\n" +
            "                \"sbxmdm\": \"yhs\",\n" +
            "                \"sbxmmc\": \"印花税申报\",\n" +
            "                \"ljdz\": \"/zjgfcsszjdzswjsbweb/pages/sb/nssb/sb_dcsb.html\",\n" +
            "                \"pzxh\": \"\",\n" +
            "                \"sssq_q\": \"\",\n" +
            "                \"sssq_z\": \"\",\n" +
            "                \"sbjzrq\": \"\",\n" +
            "                \"sbzt\": \"已申报\",\n" +
            "                \"sbrq\": \"\",\n" +
            "                \"kkzt\": \"\",\n" +
            "                \"kkrq\": \"\",\n" +
            "                \"drxx\": \"已导入\",\n" +
            "                \"qztj\": \"\",\n" +
            "                \"tsxx\": \"\",\n" +
            "                \"pzzl_dm\": \"025\",\n" +
            "                \"zsxm_dm\": \"10111\",\n" +
            "                \"nsrdzdah\": \"10213300000000006945\",\n" +
            "                \"sfdr\": \"Y\",\n" +
            "                \"sfkk\": \"Y\",\n" +
            "                \"yzpzzl_dm\": \"BDA0610794\",\n" +
            "                \"nsqx_dm\": \"\",\n" +
            "                \"sbzk\": \"1\",\n" +
            "                \"fwdz\": \"/zjgfcsszjdzswjsbweb/\",\n" +
            "                \"bjtp\": \"pages/sb/sbxm/tpsm/yhs.jpg\",\n" +
            "                \"tbsm\": \"\",\n" +
            "                \"fzsh\": \"N\",\n" +
            "                \"qsbdz\": \"pages/sb/yhs/qsb_yhssb_css.html\",\n" +
            "                \"qylx\": \"\",\n" +
            "                \"drzt\": \"\",\n" +
            "                \"cbsb\": \"0\",\n" +
            "                \"gzsb\": \"0\",\n" +
            "                \"yqsb\": \"0\",\n" +
            "                \"yqbz\": \"\",\n" +
            "                \"xmzslx\": \"\",\n" +
            "                \"kkbz\": \"\",\n" +
            "                \"acsb\": \"Y\",\n" +
            "                \"sfqz\": \"N\",\n" +
            "                \"yqwzpd\": \"N\",\n" +
            "                \"plxh\": \"-6\",\n" +
            "                \"dr_msg\": \"\",\n" +
            "                \"jcywbz\": \"\",\n" +
            "                \"wjxzdz\": \"\",\n" +
            "                \"wjdrbz\": \"\",\n" +
            "                \"gdslx\": \"2\",\n" +
            "                \"lsbbz\": \"Y\",\n" +
            "                \"lsbdz\": \"/zjgfcsszjdzswjsbweb/sbyhssbcssctrl/yhssb/Dolsb.do\",\n" +
            "                \"wcjybh\": \"\",\n" +
            "                \"sfxz\": \"Y\",\n" +
            "                \"wsid\": \"\",\n" +
            "                \"sfsqjy\": \"\",\n" +
            "                \"jsdrbz\": \"\",\n" +
            "                \"sfcjl\": \"\",\n" +
            "                \"cjxmmc\": \"\",\n" +
            "                \"ztxmbz\": \"Y\",\n" +
            "                \"dbrwbz\": \"Y\",\n" +
            "                \"yykkbz\": \"Y\",\n" +
            "                \"ztpzxh\": \"\",\n" +
            "                \"yqts\": \"\",\n" +
            "                \"zcbz\": \"\",\n" +
            "                \"ylbz\": \"\",\n" +
            "                \"bszndz\": \"http://www.zjzwfw.gov.cn/art/2017/11/10/art_49039_30360.html\",\n" +
            "                \"czgcdz\": \"https://etax.zjtax.gov.cn/SignCheck/czgc/yhs.htm\",\n" +
            "                \"blzybz\": \"Y\",\n" +
            "                \"zfwdz\": \"\",\n" +
            "                \"sfdqbb\": \"Y\",\n" +
            "                \"sfzxqbb\": \"Y\",\n" +
            "                \"hsqjbz\": \"\",\n" +
            "                \"sfjscj\": \"\",\n" +
            "                \"sfjsdr\": \"\",\n" +
            "                \"pbbtn\": \"\"\n" +
            "            },\n" +
            "            {\n" +
            "                \"sbxmdm\": \"cbj\",\n" +
            "                \"sbxmmc\": \"残疾人就业保障金缴费申报\",\n" +
            "                \"ljdz\": \"/zjgfcsszjdzswjsbweb/pages/sb/nssb/bdlb.html\",\n" +
            "                \"pzxh\": \"1218487174388\",\n" +
            "                \"sssq_q\": \"2019-04-01\",\n" +
            "                \"sssq_z\": \"2019-04-30\",\n" +
            "                \"sbjzrq\": \"2019-05-21\",\n" +
            "                \"sbzt\": \"已申报\",\n" +
            "                \"sbrq\": \"2019-05-08\",\n" +
            "                \"kkzt\": \"未扣款\",\n" +
            "                \"kkrq\": \"\",\n" +
            "                \"drxx\": \"已导入\",\n" +
            "                \"qztj\": \"\",\n" +
            "                \"tsxx\": \"\",\n" +
            "                \"pzzl_dm\": \"388\",\n" +
            "                \"zsxm_dm\": \"30218\",\n" +
            "                \"nsrdzdah\": \"10213300000000006945\",\n" +
            "                \"sfdr\": \"Y\",\n" +
            "                \"sfkk\": \"Y\",\n" +
            "                \"yzpzzl_dm\": \"BDA0610857\",\n" +
            "                \"nsqx_dm\": \"06\",\n" +
            "                \"sbzk\": \"1\",\n" +
            "                \"fwdz\": \"/zjgfcsszjdzswjsbweb/\",\n" +
            "                \"bjtp\": \"pages/sb/sbxm/tpsm/cbj.jpg\",\n" +
            "                \"tbsm\": \"\",\n" +
            "                \"fzsh\": \"N\",\n" +
            "                \"qsbdz\": \"pages/sb/cbj/qsb_cbjsb_css.html\",\n" +
            "                \"qylx\": \"\",\n" +
            "                \"drzt\": \"1\",\n" +
            "                \"cbsb\": \"0\",\n" +
            "                \"gzsb\": \"0\",\n" +
            "                \"yqsb\": \"0\",\n" +
            "                \"yqbz\": \"\",\n" +
            "                \"xmzslx\": \"\",\n" +
            "                \"kkbz\": \"0\",\n" +
            "                \"acsb\": \"N\",\n" +
            "                \"sfqz\": \"N\",\n" +
            "                \"yqwzpd\": \"N\",\n" +
            "                \"plxh\": \"-5\",\n" +
            "                \"dr_msg\": \"\",\n" +
            "                \"jcywbz\": \"\",\n" +
            "                \"wjxzdz\": \"\",\n" +
            "                \"wjdrbz\": \"\",\n" +
            "                \"gdslx\": \"2\",\n" +
            "                \"lsbbz\": \"Y\",\n" +
            "                \"lsbdz\": \"/zjgfcsszjdzswjsbweb/sb221cbjsbcssctrl/cbjsb/Dolsb.do\",\n" +
            "                \"wcjybh\": \"\",\n" +
            "                \"sfxz\": \"Y\",\n" +
            "                \"wsid\": \"\",\n" +
            "                \"sfsqjy\": \"\",\n" +
            "                \"jsdrbz\": \"\",\n" +
            "                \"sfcjl\": \"\",\n" +
            "                \"cjxmmc\": \"\",\n" +
            "                \"ztxmbz\": \"Y\",\n" +
            "                \"dbrwbz\": \"Y\",\n" +
            "                \"yykkbz\": \"Y\",\n" +
            "                \"ztpzxh\": \"\",\n" +
            "                \"yqts\": \"\",\n" +
            "                \"zcbz\": \"\",\n" +
            "                \"ylbz\": \"\",\n" +
            "                \"bszndz\": \"http://www.zjzwfw.gov.cn/art/2017/11/10/art_49039_30354.html\",\n" +
            "                \"czgcdz\": \"https://etax.zjtax.gov.cn/SignCheck/czgc/cbj.htm\",\n" +
            "                \"blzybz\": \"Y\",\n" +
            "                \"zfwdz\": \"\",\n" +
            "                \"sfdqbb\": \"Y\",\n" +
            "                \"sfzxqbb\": \"Y\",\n" +
            "                \"hsqjbz\": \"\",\n" +
            "                \"sfjscj\": \"\",\n" +
            "                \"sfjsdr\": \"\",\n" +
            "                \"pbbtn\": \"\"\n" +
            "            },\n" +
            "            {\n" +
            "                \"sbxmdm\": \"sbfdwjfr\",\n" +
            "                \"sbxmmc\": \"社会保险费缴费申报表（适用单位缴费人）\",\n" +
            "                \"ljdz\": \"/zjgfcsszjdzswjsbweb/pages/sb/nssb/bdlb.html\",\n" +
            "                \"pzxh\": \"1218487180862\",\n" +
            "                \"sssq_q\": \"2019-04-01\",\n" +
            "                \"sssq_z\": \"2019-04-30\",\n" +
            "                \"sbjzrq\": \"2019-05-21\",\n" +
            "                \"sbzt\": \"已申报\",\n" +
            "                \"sbrq\": \"2019-05-08\",\n" +
            "                \"kkzt\": \"未扣款\",\n" +
            "                \"kkrq\": \"\",\n" +
            "                \"drxx\": \"已导入\",\n" +
            "                \"qztj\": \"\",\n" +
            "                \"tsxx\": \"\",\n" +
            "                \"pzzl_dm\": \"862\",\n" +
            "                \"zsxm_dm\": \"99986\",\n" +
            "                \"nsrdzdah\": \"10213300000000006945\",\n" +
            "                \"sfdr\": \"Y\",\n" +
            "                \"sfkk\": \"Y\",\n" +
            "                \"yzpzzl_dm\": \"BDA0610222\",\n" +
            "                \"nsqx_dm\": \"06\",\n" +
            "                \"sbzk\": \"1\",\n" +
            "                \"fwdz\": \"/zjgfcsszjdzswjsbweb/\",\n" +
            "                \"bjtp\": \"pages/sb/sbxm/tpsm/sbfdwjfr.jpg\",\n" +
            "                \"tbsm\": \"pages/sb/sbxm/tbsm/shbx_sm.html\",\n" +
            "                \"fzsh\": \"N\",\n" +
            "                \"qsbdz\": \"pages/sb/shbxsbb/qsb.html\",\n" +
            "                \"qylx\": \"\",\n" +
            "                \"drzt\": \"1\",\n" +
            "                \"cbsb\": \"0\",\n" +
            "                \"gzsb\": \"0\",\n" +
            "                \"yqsb\": \"0\",\n" +
            "                \"yqbz\": \"\",\n" +
            "                \"xmzslx\": \"\",\n" +
            "                \"kkbz\": \"0\",\n" +
            "                \"acsb\": \"N\",\n" +
            "                \"sfqz\": \"Y\",\n" +
            "                \"yqwzpd\": \"N\",\n" +
            "                \"plxh\": \"13\",\n" +
            "                \"dr_msg\": \"\",\n" +
            "                \"jcywbz\": \"\",\n" +
            "                \"wjxzdz\": \"\",\n" +
            "                \"wjdrbz\": \"\",\n" +
            "                \"gdslx\": \"4\",\n" +
            "                \"lsbbz\": \"N\",\n" +
            "                \"lsbdz\": \"/zjgfcsszjdzswjsbweb/\",\n" +
            "                \"wcjybh\": \"\",\n" +
            "                \"sfxz\": \"Y\",\n" +
            "                \"wsid\": \"\",\n" +
            "                \"sfsqjy\": \"N\",\n" +
            "                \"jsdrbz\": \"\",\n" +
            "                \"sfcjl\": \"\",\n" +
            "                \"cjxmmc\": \"\",\n" +
            "                \"ztxmbz\": \"Y\",\n" +
            "                \"dbrwbz\": \"Y\",\n" +
            "                \"yykkbz\": \"Y\",\n" +
            "                \"ztpzxh\": \"\",\n" +
            "                \"yqts\": \"\",\n" +
            "                \"zcbz\": \"N\",\n" +
            "                \"ylbz\": \"\",\n" +
            "                \"bszndz\": \"http://www.zjzwfw.gov.cn/art/2017/11/10/art_49039_30355.html\",\n" +
            "                \"czgcdz\": \"https://etax.zjtax.gov.cn/SignCheck/czgc/sbfdwjfr.htm\",\n" +
            "                \"blzybz\": \"Y\",\n" +
            "                \"zfwdz\": \"\",\n" +
            "                \"sfdqbb\": \"Y\",\n" +
            "                \"sfzxqbb\": \"Y\",\n" +
            "                \"hsqjbz\": \"\",\n" +
            "                \"sfjscj\": \"\",\n" +
            "                \"sfjsdr\": \"\",\n" +
            "                \"pbbtn\": \"XG\"\n" +
            "            },\n" +
            "            {\n" +
            "                \"sbxmdm\": \"ccs\",\n" +
            "                \"sbxmmc\": \"车船税申报\",\n" +
            "                \"ljdz\": \"/zjgfcsszjdzswjsbweb/pages/sb/nssb/bdlb.html\",\n" +
            "                \"pzxh\": \"\",\n" +
            "                \"sssq_q\": \"2019-01-01\",\n" +
            "                \"sssq_z\": \"2019-12-31\",\n" +
            "                \"sbjzrq\": \"\",\n" +
            "                \"sbzt\": \"\",\n" +
            "                \"sbrq\": \"\",\n" +
            "                \"kkzt\": \"\",\n" +
            "                \"kkrq\": \"\",\n" +
            "                \"drxx\": \"\",\n" +
            "                \"qztj\": \"\",\n" +
            "                \"tsxx\": \"\",\n" +
            "                \"pzzl_dm\": \"203\",\n" +
            "                \"zsxm_dm\": \"10114\",\n" +
            "                \"nsrdzdah\": \"10213300000000006945\",\n" +
            "                \"sfdr\": \"Y\",\n" +
            "                \"sfkk\": \"Y\",\n" +
            "                \"yzpzzl_dm\": \"BDA0610750\",\n" +
            "                \"nsqx_dm\": \"\",\n" +
            "                \"sbzk\": \"\",\n" +
            "                \"fwdz\": \"/zjgfcsszjdzswjsbweb/\",\n" +
            "                \"bjtp\": \"pages/sb/sbxm/tpsm/ccssb.jpg\",\n" +
            "                \"tbsm\": \"\",\n" +
            "                \"fzsh\": \"N\",\n" +
            "                \"qsbdz\": \"pages/sb/ccs/qsb_ccssb_css.html\",\n" +
            "                \"qylx\": \"\",\n" +
            "                \"drzt\": \"\",\n" +
            "                \"cbsb\": \"0\",\n" +
            "                \"gzsb\": \"0\",\n" +
            "                \"yqsb\": \"0\",\n" +
            "                \"yqbz\": \"\",\n" +
            "                \"xmzslx\": \"\",\n" +
            "                \"kkbz\": \"\",\n" +
            "                \"acsb\": \"N\",\n" +
            "                \"sfqz\": \"N\",\n" +
            "                \"yqwzpd\": \"N\",\n" +
            "                \"plxh\": \"114\",\n" +
            "                \"dr_msg\": \"\",\n" +
            "                \"jcywbz\": \"\",\n" +
            "                \"wjxzdz\": \"\",\n" +
            "                \"wjdrbz\": \"\",\n" +
            "                \"gdslx\": \"2\",\n" +
            "                \"lsbbz\": \"N\",\n" +
            "                \"lsbdz\": \"/zjgfcsszjdzswjsbweb/\",\n" +
            "                \"wcjybh\": \"\",\n" +
            "                \"sfxz\": \"Y\",\n" +
            "                \"wsid\": \"\",\n" +
            "                \"sfsqjy\": \"\",\n" +
            "                \"jsdrbz\": \"\",\n" +
            "                \"sfcjl\": \"\",\n" +
            "                \"cjxmmc\": \"\",\n" +
            "                \"ztxmbz\": \"Y\",\n" +
            "                \"dbrwbz\": \"\",\n" +
            "                \"yykkbz\": \"Y\",\n" +
            "                \"ztpzxh\": \"\",\n" +
            "                \"yqts\": \"\",\n" +
            "                \"zcbz\": \"\",\n" +
            "                \"ylbz\": \"\",\n" +
            "                \"bszndz\": \"http://www.zjzwfw.gov.cn/art/2017/11/10/art_49039_30370.html\",\n" +
            "                \"czgcdz\": \"https://etax.zjtax.gov.cn/SignCheck/czgc/ccs.htm\",\n" +
            "                \"blzybz\": \"Y\",\n" +
            "                \"zfwdz\": \"\",\n" +
            "                \"sfdqbb\": \"\",\n" +
            "                \"sfzxqbb\": \"\",\n" +
            "                \"hsqjbz\": \"\",\n" +
            "                \"sfjscj\": \"\",\n" +
            "                \"sfjsdr\": \"\",\n" +
            "                \"pbbtn\": \"\"\n" +
            "            },\n" +
            "            {\n" +
            "                \"sbxmdm\": \"gdzys\",\n" +
            "                \"sbxmmc\": \"耕地占用税申报\",\n" +
            "                \"ljdz\": \"/zjgfcsszjdzswjsbweb/pages/sb/nssb/sb_dcsb.html\",\n" +
            "                \"pzxh\": \"\",\n" +
            "                \"sssq_q\": \"\",\n" +
            "                \"sssq_z\": \"\",\n" +
            "                \"sbjzrq\": \"\",\n" +
            "                \"sbzt\": \"\",\n" +
            "                \"sbrq\": \"\",\n" +
            "                \"kkzt\": \"\",\n" +
            "                \"kkrq\": \"\",\n" +
            "                \"drxx\": \"\",\n" +
            "                \"qztj\": \"\",\n" +
            "                \"tsxx\": \"\",\n" +
            "                \"pzzl_dm\": \"039\",\n" +
            "                \"zsxm_dm\": \"10118\",\n" +
            "                \"nsrdzdah\": \"10213300000000006945\",\n" +
            "                \"sfdr\": \"Y\",\n" +
            "                \"sfkk\": \"Y\",\n" +
            "                \"yzpzzl_dm\": \"BDA0610007\",\n" +
            "                \"nsqx_dm\": \"\",\n" +
            "                \"sbzk\": \"\",\n" +
            "                \"fwdz\": \"/zjgfcsszjdzswjsbweb/\",\n" +
            "                \"bjtp\": \"pages/sb/sbxm/tpsm/gdzys.jpg\",\n" +
            "                \"tbsm\": \"\",\n" +
            "                \"fzsh\": \"N\",\n" +
            "                \"qsbdz\": \"pages/sb/gdzys/qsb_gdzyssb_css.html\",\n" +
            "                \"qylx\": \"\",\n" +
            "                \"drzt\": \"\",\n" +
            "                \"cbsb\": \"0\",\n" +
            "                \"gzsb\": \"0\",\n" +
            "                \"yqsb\": \"0\",\n" +
            "                \"yqbz\": \"\",\n" +
            "                \"xmzslx\": \"\",\n" +
            "                \"kkbz\": \"\",\n" +
            "                \"acsb\": \"Y\",\n" +
            "                \"sfqz\": \"N\",\n" +
            "                \"yqwzpd\": \"N\",\n" +
            "                \"plxh\": \"202\",\n" +
            "                \"dr_msg\": \"\",\n" +
            "                \"jcywbz\": \"\",\n" +
            "                \"wjxzdz\": \"\",\n" +
            "                \"wjdrbz\": \"\",\n" +
            "                \"gdslx\": \"2\",\n" +
            "                \"lsbbz\": \"N\",\n" +
            "                \"lsbdz\": \"/zjgfcsszjdzswjsbweb/\",\n" +
            "                \"wcjybh\": \"\",\n" +
            "                \"sfxz\": \"Y\",\n" +
            "                \"wsid\": \"\",\n" +
            "                \"sfsqjy\": \"\",\n" +
            "                \"jsdrbz\": \"\",\n" +
            "                \"sfcjl\": \"\",\n" +
            "                \"cjxmmc\": \"\",\n" +
            "                \"ztxmbz\": \"Y\",\n" +
            "                \"dbrwbz\": \"\",\n" +
            "                \"yykkbz\": \"N\",\n" +
            "                \"ztpzxh\": \"\",\n" +
            "                \"yqts\": \"\",\n" +
            "                \"zcbz\": \"\",\n" +
            "                \"ylbz\": \"\",\n" +
            "                \"bszndz\": \"http://www.zjzwfw.gov.cn/art/2017/11/10/art_49039_30365.html\",\n" +
            "                \"czgcdz\": \"https://etax.zjtax.gov.cn/SignCheck/czgc/gdzys.htm\",\n" +
            "                \"blzybz\": \"Y\",\n" +
            "                \"zfwdz\": \"\",\n" +
            "                \"sfdqbb\": \"\",\n" +
            "                \"sfzxqbb\": \"\",\n" +
            "                \"hsqjbz\": \"\",\n" +
            "                \"sfjscj\": \"\",\n" +
            "                \"sfjsdr\": \"\",\n" +
            "                \"pbbtn\": \"\"\n" +
            "            },\n" +
            "            {\n" +
            "                \"sbxmdm\": \"hbsb\",\n" +
            "                \"sbxmmc\": \"环境保护税纳税申报表（按次申报）\",\n" +
            "                \"ljdz\": \"/zjgfcsszjdzswjsbweb/pages/sb/nssb/sb_dcsb.html\",\n" +
            "                \"pzxh\": \"\",\n" +
            "                \"sssq_q\": \"\",\n" +
            "                \"sssq_z\": \"\",\n" +
            "                \"sbjzrq\": \"\",\n" +
            "                \"sbzt\": \"\",\n" +
            "                \"sbrq\": \"\",\n" +
            "                \"kkzt\": \"\",\n" +
            "                \"kkrq\": \"\",\n" +
            "                \"drxx\": \"\",\n" +
            "                \"qztj\": \"\",\n" +
            "                \"tsxx\": \"\",\n" +
            "                \"pzzl_dm\": \"223\",\n" +
            "                \"zsxm_dm\": \"10121\",\n" +
            "                \"nsrdzdah\": \"10213300000000006945\",\n" +
            "                \"sfdr\": \"Y\",\n" +
            "                \"sfkk\": \"Y\",\n" +
            "                \"yzpzzl_dm\": \"BDA0610986\",\n" +
            "                \"nsqx_dm\": \"\",\n" +
            "                \"sbzk\": \"\",\n" +
            "                \"fwdz\": \"/zjgfcsszjdzswjsbweb/\",\n" +
            "                \"bjtp\": \"pages/sb/sbxm/tpsm/hbsacsb.jpg\",\n" +
            "                \"tbsm\": \"\",\n" +
            "                \"fzsh\": \"N\",\n" +
            "                \"qsbdz\": \"pages/sb/hbs/qsb_hbssbb_css.html\",\n" +
            "                \"qylx\": \"\",\n" +
            "                \"drzt\": \"\",\n" +
            "                \"cbsb\": \"0\",\n" +
            "                \"gzsb\": \"0\",\n" +
            "                \"yqsb\": \"0\",\n" +
            "                \"yqbz\": \"\",\n" +
            "                \"xmzslx\": \"\",\n" +
            "                \"kkbz\": \"\",\n" +
            "                \"acsb\": \"Y\",\n" +
            "                \"sfqz\": \"N\",\n" +
            "                \"yqwzpd\": \"N\",\n" +
            "                \"plxh\": \"203\",\n" +
            "                \"dr_msg\": \"\",\n" +
            "                \"jcywbz\": \"\",\n" +
            "                \"wjxzdz\": \"\",\n" +
            "                \"wjdrbz\": \"\",\n" +
            "                \"gdslx\": \"2\",\n" +
            "                \"lsbbz\": \"N\",\n" +
            "                \"lsbdz\": \"/zjgfcsszjdzswjsbweb/\",\n" +
            "                \"wcjybh\": \"\",\n" +
            "                \"sfxz\": \"Y\",\n" +
            "                \"wsid\": \"\",\n" +
            "                \"sfsqjy\": \"\",\n" +
            "                \"jsdrbz\": \"\",\n" +
            "                \"sfcjl\": \"\",\n" +
            "                \"cjxmmc\": \"\",\n" +
            "                \"ztxmbz\": \"Y\",\n" +
            "                \"dbrwbz\": \"\",\n" +
            "                \"yykkbz\": \"N\",\n" +
            "                \"ztpzxh\": \"\",\n" +
            "                \"yqts\": \"\",\n" +
            "                \"zcbz\": \"\",\n" +
            "                \"ylbz\": \"\",\n" +
            "                \"bszndz\": \"\",\n" +
            "                \"czgcdz\": \"https://etax.zjtax.gov.cn/SignCheck/czgc/hbsb.htm\",\n" +
            "                \"blzybz\": \"N\",\n" +
            "                \"zfwdz\": \"\",\n" +
            "                \"sfdqbb\": \"\",\n" +
            "                \"sfzxqbb\": \"\",\n" +
            "                \"hsqjbz\": \"\",\n" +
            "                \"sfjscj\": \"\",\n" +
            "                \"sfjsdr\": \"\",\n" +
            "                \"pbbtn\": \"\"\n" +
            "            },\n" +
            "            {\n" +
            "                \"sbxmdm\": \"jscgrgbab\",\n" +
            "                \"sbxmmc\": \"技术成果入股备案表(选报)\",\n" +
            "                \"ljdz\": \"/zjgfzjdzswjsbweb/pages/sb/nssb/sb_dcsb.html\",\n" +
            "                \"pzxh\": \"\",\n" +
            "                \"sssq_q\": \"2019-04-01\",\n" +
            "                \"sssq_z\": \"2019-04-30\",\n" +
            "                \"sbjzrq\": \"\",\n" +
            "                \"sbzt\": \"\",\n" +
            "                \"sbrq\": \"\",\n" +
            "                \"kkzt\": \"\",\n" +
            "                \"kkrq\": \"\",\n" +
            "                \"drxx\": \"\",\n" +
            "                \"qztj\": \"\",\n" +
            "                \"tsxx\": \"\",\n" +
            "                \"pzzl_dm\": \"505\",\n" +
            "                \"zsxm_dm\": \"10104\",\n" +
            "                \"nsrdzdah\": \"10213300000000006945\",\n" +
            "                \"sfdr\": \"Y\",\n" +
            "                \"sfkk\": \"Y\",\n" +
            "                \"yzpzzl_dm\": \"\",\n" +
            "                \"nsqx_dm\": \"\",\n" +
            "                \"sbzk\": \"\",\n" +
            "                \"fwdz\": \"/zjgfzjdzswjsbweb/\",\n" +
            "                \"bjtp\": \"pages/sb/sbxm/tpsm/jscg.jpg\",\n" +
            "                \"tbsm\": \"pages/sb/sbxm/tbsm/jscg_sm.html\",\n" +
            "                \"fzsh\": \"N\",\n" +
            "                \"qsbdz\": \"pages/sb/qt/jscgrgbab/qsb.html\",\n" +
            "                \"qylx\": \"\",\n" +
            "                \"drzt\": \"\",\n" +
            "                \"cbsb\": \"0\",\n" +
            "                \"gzsb\": \"0\",\n" +
            "                \"yqsb\": \"0\",\n" +
            "                \"yqbz\": \"\",\n" +
            "                \"xmzslx\": \"\",\n" +
            "                \"kkbz\": \"\",\n" +
            "                \"acsb\": \"Y\",\n" +
            "                \"sfqz\": \"N\",\n" +
            "                \"yqwzpd\": \"N\",\n" +
            "                \"plxh\": \"900\",\n" +
            "                \"dr_msg\": \"\",\n" +
            "                \"jcywbz\": \"\",\n" +
            "                \"wjxzdz\": \"\",\n" +
            "                \"wjdrbz\": \"\",\n" +
            "                \"gdslx\": \"1\",\n" +
            "                \"lsbbz\": \"N\",\n" +
            "                \"lsbdz\": \"/zjgfzjdzswjsbweb/\",\n" +
            "                \"wcjybh\": \"\",\n" +
            "                \"sfxz\": \"Y\",\n" +
            "                \"wsid\": \"\",\n" +
            "                \"sfsqjy\": \"\",\n" +
            "                \"jsdrbz\": \"\",\n" +
            "                \"sfcjl\": \"\",\n" +
            "                \"cjxmmc\": \"\",\n" +
            "                \"ztxmbz\": \"N\",\n" +
            "                \"dbrwbz\": \"\",\n" +
            "                \"yykkbz\": \"N\",\n" +
            "                \"ztpzxh\": \"\",\n" +
            "                \"yqts\": \"\",\n" +
            "                \"zcbz\": \"\",\n" +
            "                \"ylbz\": \"\",\n" +
            "                \"bszndz\": \"\",\n" +
            "                \"czgcdz\": \"https://etax.zjtax.gov.cn/SignCheck/czgc/jscgrgbab.htm\",\n" +
            "                \"blzybz\": \"N\",\n" +
            "                \"zfwdz\": \"\",\n" +
            "                \"sfdqbb\": \"\",\n" +
            "                \"sfzxqbb\": \"\",\n" +
            "                \"hsqjbz\": \"\",\n" +
            "                \"sfjscj\": \"\",\n" +
            "                \"sfjsdr\": \"\",\n" +
            "                \"pbbtn\": \"\"\n" +
            "            },\n" +
            "            {\n" +
            "                \"sbxmdm\": \"hgpzdksc\",\n" +
            "                \"sbxmmc\": \"海关凭证抵扣上传\",\n" +
            "                \"ljdz\": \"/zjgfctais2/wssb/ybnsr2012/zzs_hg.jsp\",\n" +
            "                \"pzxh\": \"\",\n" +
            "                \"sssq_q\": \"\",\n" +
            "                \"sssq_z\": \"\",\n" +
            "                \"sbjzrq\": \"\",\n" +
            "                \"sbzt\": \"\",\n" +
            "                \"sbrq\": \"\",\n" +
            "                \"kkzt\": \"\",\n" +
            "                \"kkrq\": \"\",\n" +
            "                \"drxx\": \"\",\n" +
            "                \"qztj\": \"\",\n" +
            "                \"tsxx\": \"\",\n" +
            "                \"pzzl_dm\": \"990\",\n" +
            "                \"zsxm_dm\": \"10101\",\n" +
            "                \"nsrdzdah\": \"10213300000000006945\",\n" +
            "                \"sfdr\": \"N\",\n" +
            "                \"sfkk\": \"N\",\n" +
            "                \"yzpzzl_dm\": \"\",\n" +
            "                \"nsqx_dm\": \"\",\n" +
            "                \"sbzk\": \"\",\n" +
            "                \"fwdz\": \"/zjgfctais2/wssb/\",\n" +
            "                \"bjtp\": \"\",\n" +
            "                \"tbsm\": \"\",\n" +
            "                \"fzsh\": \"N\",\n" +
            "                \"qsbdz\": \"\",\n" +
            "                \"qylx\": \"\",\n" +
            "                \"drzt\": \"\",\n" +
            "                \"cbsb\": \"0\",\n" +
            "                \"gzsb\": \"0\",\n" +
            "                \"yqsb\": \"0\",\n" +
            "                \"yqbz\": \"\",\n" +
            "                \"xmzslx\": \"\",\n" +
            "                \"kkbz\": \"\",\n" +
            "                \"acsb\": \"N\",\n" +
            "                \"sfqz\": \"N\",\n" +
            "                \"yqwzpd\": \"N\",\n" +
            "                \"plxh\": \"999\",\n" +
            "                \"dr_msg\": \"\",\n" +
            "                \"jcywbz\": \"\",\n" +
            "                \"wjxzdz\": \"\",\n" +
            "                \"wjdrbz\": \"\",\n" +
            "                \"gdslx\": \"1\",\n" +
            "                \"lsbbz\": \"N\",\n" +
            "                \"lsbdz\": \"/zjgfctais2/wssb/\",\n" +
            "                \"wcjybh\": \"\",\n" +
            "                \"sfxz\": \"Y\",\n" +
            "                \"wsid\": \"\",\n" +
            "                \"sfsqjy\": \"\",\n" +
            "                \"jsdrbz\": \"\",\n" +
            "                \"sfcjl\": \"\",\n" +
            "                \"cjxmmc\": \"\",\n" +
            "                \"ztxmbz\": \"N\",\n" +
            "                \"dbrwbz\": \"\",\n" +
            "                \"yykkbz\": \"N\",\n" +
            "                \"ztpzxh\": \"\",\n" +
            "                \"yqts\": \"\",\n" +
            "                \"zcbz\": \"\",\n" +
            "                \"ylbz\": \"\",\n" +
            "                \"bszndz\": \"\",\n" +
            "                \"czgcdz\": \"https://etax.zjtax.gov.cn/SignCheck/czgc/hgpzdksc.htm\",\n" +
            "                \"blzybz\": \"Y\",\n" +
            "                \"zfwdz\": \"\",\n" +
            "                \"sfdqbb\": \"\",\n" +
            "                \"sfzxqbb\": \"\",\n" +
            "                \"hsqjbz\": \"\",\n" +
            "                \"sfjscj\": \"\",\n" +
            "                \"sfjsdr\": \"\",\n" +
            "                \"pbbtn\": \"\"\n" +
            "            }\n" +
            "        ],\n" +
            "        \"sbxm\": \"ZZS_YBNSR_SBZK=1110010111000111010000000000000000000030020901010022000000100002205000@ZZS_SSSQQ=2019-04-01@@ZZS_SSSQZ=2019-04-30@@ZZS_XGM_SBZK=999@XFS_SBZK=999@QYSDS_SBZK=999@QYSDS_ND_SBZK=999@QYSDS_ND_SSSQ_Q=2019-05-14@QYSDS_ND_YWWL_SBZK=999@@SDSBA_ND_SBZK=999@GRSDS_SBZK=999@SSDC_SBZK=999@@QYSDS_FJM_SBZK=999@@QYSDS_FJM_ND_SBZK=999@@DQY_SBZK=999@@KJB_SBZK=999@@NDZCSS_SBZK=999@@FQDQDZ_JJ_SBZK=999@@WHSYJSF_SBZK=999@@CWBB_2013_SBZK=999@@CWBB_2013_SBZK_ND=999@@JZJT_SBZK=999@@SKWGQYBGB_SBZK=999@@CGWGQYBGB_SBZK=999@@QYSDS_ZSBG_SBZK=999@@QYCZCLBGB_SBZK=999@@QYZCGQHZCLBGB_SBZK=999@@FHBTZDYNSTZ_SBZK=999@@ZZSYJSK_SBZK=999@@CWBB_HB_SBZK=999@@DYNSBAB_SBZK=999@@YFXMGJB_SBZK=999@@YFZCHZB_SBZK=999@@JMSTJ_SBZK=999@@NSFW_SBZK=999@@WZSDS_SBZK=999@@SSDC_2004_SBZK=999@@SSDC_2005_SBZK=999@@ZZSDE_SBZK=999@@CWBB_SBZK=999@@105_yqgz=1@\",\n" +
            "        \"tsnsrbz\": false,\n" +
            "        \"jcxxretbo\": {\n" +
            "            \"nsrdzdah\": \"10213300000000006945\",\n" +
            "            \"sbxmdm\": \"\",\n" +
            "            \"sbxmmc\": \"\",\n" +
            "            \"bddm\": \"\",\n" +
            "            \"bdmc\": \"\",\n" +
            "            \"sssq_q\": null,\n" +
            "            \"sssq_z\": null,\n" +
            "            \"sbqx\": null,\n" +
            "            \"sqq\": \"\",\n" +
            "            \"sqz\": \"\",\n" +
            "            \"pzxh\": \"\",\n" +
            "            \"nsrmc\": \"\",\n" +
            "            \"nsrsbh\": \"\",\n" +
            "            \"tbrq\": \"\",\n" +
            "            \"qzjy\": \"\",\n" +
            "            \"tjjy\": \"\",\n" +
            "            \"dosess\": \"\",\n" +
            "            \"sbzt\": \"\",\n" +
            "            \"sbzk\": \"\",\n" +
            "            \"yearmonth\": \"\",\n" +
            "            \"month\": \"\",\n" +
            "            \"sbrq\": \"2019-05-14\",\n" +
            "            \"nsr_swjg_dm\": \"\",\n" +
            "            \"nsqx_dm\": \"\",\n" +
            "            \"pzzl_dm\": \"\",\n" +
            "            \"zsxm_dm\": \"\",\n" +
            "            \"zspm_dm\": \"\",\n" +
            "            \"zszm_dm\": \"\",\n" +
            "            \"kyslrq\": \"\",\n" +
            "            \"hy_dm\": \"\",\n" +
            "            \"shxydm\": \"\",\n" +
            "            \"djzclx_dm\": \"\",\n" +
            "            \"nsrsbh_new\": \"\",\n" +
            "            \"nsrsbh_old\": \"\",\n" +
            "            \"sbh\": \"\",\n" +
            "            \"qylx\": \"\",\n" +
            "            \"zdts\": \"\",\n" +
            "            \"tbsm\": \"\",\n" +
            "            \"qsbdz\": \"\",\n" +
            "            \"drzt\": \"\",\n" +
            "            \"hymc\": \"\",\n" +
            "            \"xmzslx\": \"1\",\n" +
            "            \"dqyhxm\": \"\",\n" +
            "            \"yqbz\": \"\",\n" +
            "            \"yqsb\": \"\",\n" +
            "            \"cbsb\": \"\",\n" +
            "            \"gzsb\": \"\",\n" +
            "            \"sfdr\": \"\",\n" +
            "            \"fzsh\": \"\",\n" +
            "            \"kkbz\": \"\",\n" +
            "            \"acsb\": \"\",\n" +
            "            \"jcywbz\": \"\",\n" +
            "            \"sfyctj\": \"\",\n" +
            "            \"wjxzdz\": \"\",\n" +
            "            \"wjdrbz\": \"\",\n" +
            "            \"methodname\": \"\",\n" +
            "            \"dsdjxh\": \"10213300000000006945\",\n" +
            "            \"dssjgsdq\": \"\",\n" +
            "            \"sbbdlist\": [],\n" +
            "            \"zrrxx\": {\n" +
            "                \"djxh\": \"\",\n" +
            "                \"sfzjlx_dm\": \"\",\n" +
            "                \"sfzjhm\": \"\",\n" +
            "                \"xm\": \"\",\n" +
            "                \"nsrsbh\": \"\",\n" +
            "                \"zlsfqq\": \"\",\n" +
            "                \"lydm\": \"\",\n" +
            "                \"yxbz\": \"\",\n" +
            "                \"bdbz\": \"\",\n" +
            "                \"fxbz\": \"\",\n" +
            "                \"zrrlx_dm\": \"\",\n" +
            "                \"xybz\": \"\",\n" +
            "                \"sjgsdq\": \"\",\n" +
            "                \"cjxm\": \"\",\n" +
            "                \"lyqd_dm\": \"\",\n" +
            "                \"swsx_dm\": \"\",\n" +
            "                \"slswjg_dm\": \"\",\n" +
            "                \"sjyxzt\": \"\"\n" +
            "            },\n" +
            "            \"wcjybh\": \"\",\n" +
            "            \"sblx\": \"\",\n" +
            "            \"bydjuuid\": \"\",\n" +
            "            \"frzjlx_dm\": \"\",\n" +
            "            \"zjhm\": \"\",\n" +
            "            \"sfqz\": \"\",\n" +
            "            \"sfsqjy\": \"\",\n" +
            "            \"gsdjxh\": \"\",\n" +
            "            \"jdxz_dm\": \"\",\n" +
            "            \"xtbblxswjg\": \"133\",\n" +
            "            \"sfkk\": \"\",\n" +
            "            \"ztxmbz\": \"\",\n" +
            "            \"fwdz\": \"\",\n" +
            "            \"xzqh_dm\": \"\",\n" +
            "            \"gdslx\": \"\",\n" +
            "            \"ztpzxh\": \"\",\n" +
            "            \"zcbz\": \"\",\n" +
            "            \"ylbz\": \"\",\n" +
            "            \"tsbz\": \"\",\n" +
            "            \"sjly\": \"\",\n" +
            "            \"jylx\": \"\",\n" +
            "            \"tzcode\": \"\",\n" +
            "            \"cxqq\": \"\",\n" +
            "            \"cxqz\": \"\",\n" +
            "            \"xmfwly\": \"\",\n" +
            "            \"bqsfsyxgmyhzc\": null,\n" +
            "            \"phjmxzDm\": null,\n" +
            "            \"phjzbl\": null,\n" +
            "            \"phjmswsxDm\": null,\n" +
            "            \"phjmse\": null,\n" +
            "            \"syxgmjzzcqssj\": null,\n" +
            "            \"syxgmjzzczzsj\": null\n" +
            "        },\n" +
            "        \"nsrxx\": \"DJSJ=N@NSRSBH=91330109MA2GLE0WXT@NSRDZDAH=10213300000000006945@NSRMC=杭州萧美装饰材料有限公司@NSR_SWJG_DM=13301099200@FDDBRMC=沃红农@HY_DM=5289@HY_MC=其他室内装饰材料零售@NSRZT_MC=正常@SCJYDZ=浙江省杭州市萧山区经济技术开发区桥南区块鸿达路309号@YZBM=      @DHHM=@SJDHHM=@BSRMC=沃红农@DJZCLX_MC=私营有限责任公司@NSR_SWJG_MC=国家税务总局杭州市萧山区税务局经济技术开发区税务所@YH_MC=中国农业银行杭州和睦支行@YHZH=19010201040015697@YHZL=1103331001026@SQH=999@SBRQ=2019-05-14 145152@NSR_SWJG_UPLOAD=13301/13301090000/@UPLOAD_IP=@YSLW_IP=@URL=@CXBZ=@FB2_TZ=@BCSB_BZ=@QDS_BZ=0@DZFPZJ=@SFYHZ=0@WSSB_AUTH=1@NSRSBH_OLD=91330109MA2GLE0WXT@NSRSBH_NEW=91330109MA2GLE0WXT@YYKK=Y@YDHH=0@WHMSG=@WMQY_BZ=Y@WBPC=N@WSSB_PASS=N@VPDN_PASS=N@DJ_JBXX=Y@QRBZ=N@JSTGG=N@WSSBIP=@CKTSIP=@WLFPIP=@MAINIP=@YZS=N@YYSBZ=@JKIP=@HZDS_BZ=N@FTPIP=@HZDZSWJIP=@DSDJXH=10213300000000006945@MSBA_LSQY=0@MSBA_JZJT=0@MSBA_JYZS=0@CXFWMSG=系统数据正在初始化处理，查询服务暂时关闭@PZXH=1218487170@PZXH_ND=@PZXH_SSDC=0@\",\n" +
            "        \"xxmap\": {\n" +
            "            \"SCJYDZ\": \"浙江省杭州市萧山区经济技术开发区桥南区块鸿达路309号\",\n" +
            "            \"dsInfo\": {\n" +
            "                \"SCJYDZ\": \"浙江省杭州市萧山区经济技术开发区桥南区块鸿达路309号\",\n" +
            "                \"ZGSWSKFJ_DM\": \"13301099200\",\n" +
            "                \"GDGHLX_DM\": \"1\",\n" +
            "                \"SJGSDQ\": \"13301099200\",\n" +
            "                \"KZZTDJLX_DM\": \"1110\",\n" +
            "                \"ZCDZXZQHSZ_DM\": \"330109\",\n" +
            "                \"FDDBRXM\": \"沃红农\",\n" +
            "                \"FDDBRSFZJLX_DM\": \"201\",\n" +
            "                \"GDSLX_DM\": \"1\",\n" +
            "                \"ZCDZ\": \"浙江省杭州市萧山区经济技术开发区桥南区块鸿达路309号\",\n" +
            "                \"DJXH\": \"10213300000000006945\",\n" +
            "                \"SCJYDZXZQHSZ_DM\": \"330109\",\n" +
            "                \"HY_DM\": \"5289\",\n" +
            "                \"FJMQYBZ\": \"N\",\n" +
            "                \"SHXYDM\": \"91330109MA2GLE0WXT\",\n" +
            "                \"NSRSBH\": \"91330109MA2GLE0WXT\",\n" +
            "                \"YXBZ\": \"Y\",\n" +
            "                \"DJRQ\": \"2019-04-09\",\n" +
            "                \"DJJG_DM\": \"13301099200\",\n" +
            "                \"SFUUID\": \"8563e12f52944dc4bb74fdd2d8147a74\",\n" +
            "                \"NSRZT_DM\": \"03\",\n" +
            "                \"KQCCSZTDJBZ\": \"N\",\n" +
            "                \"DJZCLX_DM\": \"173\",\n" +
            "                \"NSRMC\": \"杭州萧美装饰材料有限公司\",\n" +
            "                \"ZZJG_DM\": \"MA2GLE0WX\",\n" +
            "                \"FDDBRSFZJHM\": \"330121196111213318\",\n" +
            "                \"JDXZ_DM\": \"330109904\",\n" +
            "                \"SWDJBLBZ\": \"Y\",\n" +
            "                \"SWJGMC\": \"国家税务总局杭州市萧山区税务局经济技术开发区税务所\",\n" +
            "                \"DWLSGX_DM\": \"51\",\n" +
            "                \"ZGSWJ_DM\": \"13301090000\"\n" +
            "            },\n" +
            "            \"SWJG_DM\": \"13301099200\",\n" +
            "            \"nsrxx\": {\n" +
            "                \"SCJYDZ\": \"浙江省杭州市萧山区经济技术开发区桥南区块鸿达路309号\",\n" +
            "                \"ZGSWSKFJ_DM\": \"13301099200\",\n" +
            "                \"GDGHLX_DM\": \"1\",\n" +
            "                \"SJGSDQ\": \"13301099200\",\n" +
            "                \"KZZTDJLX_DM\": \"1110\",\n" +
            "                \"ZCDZXZQHSZ_DM\": \"330109\",\n" +
            "                \"FDDBRXM\": \"沃红农\",\n" +
            "                \"FDDBRSFZJLX_DM\": \"201\",\n" +
            "                \"GDSLX_DM\": \"1\",\n" +
            "                \"ZCDZ\": \"浙江省杭州市萧山区经济技术开发区桥南区块鸿达路309号\",\n" +
            "                \"DJXH\": \"10213300000000006945\",\n" +
            "                \"SCJYDZXZQHSZ_DM\": \"330109\",\n" +
            "                \"HY_DM\": \"5289\",\n" +
            "                \"FJMQYBZ\": \"N\",\n" +
            "                \"SHXYDM\": \"91330109MA2GLE0WXT\",\n" +
            "                \"NSRSBH\": \"91330109MA2GLE0WXT\",\n" +
            "                \"YXBZ\": \"Y\",\n" +
            "                \"DJRQ\": \"2019-04-09\",\n" +
            "                \"DJJG_DM\": \"13301099200\",\n" +
            "                \"SFUUID\": \"8563e12f52944dc4bb74fdd2d8147a74\",\n" +
            "                \"NSRZT_DM\": \"03\",\n" +
            "                \"KQCCSZTDJBZ\": \"N\",\n" +
            "                \"DJZCLX_DM\": \"173\",\n" +
            "                \"NSRMC\": \"杭州萧美装饰材料有限公司\",\n" +
            "                \"ZZJG_DM\": \"MA2GLE0WX\",\n" +
            "                \"FDDBRSFZJHM\": \"330121196111213318\",\n" +
            "                \"JDXZ_DM\": \"330109904\",\n" +
            "                \"SWDJBLBZ\": \"Y\",\n" +
            "                \"SWJGMC\": \"国家税务总局杭州市萧山区税务局经济技术开发区税务所\",\n" +
            "                \"DWLSGX_DM\": \"51\",\n" +
            "                \"ZGSWJ_DM\": \"13301090000\"\n" +
            "            },\n" +
            "            \"SFUUID\": \"8563e12f52944dc4bb74fdd2d8147a74\",\n" +
            "            \"FDDBRXM\": \"沃红农\",\n" +
            "            \"NSRMC\": \"杭州萧美装饰材料有限公司\",\n" +
            "            \"XMING\": \"沃红农\",\n" +
            "            \"YEAR\": \"2019\",\n" +
            "            \"DJXH\": \"10213300000000006945\",\n" +
            "            \"SFLX\": \"02\",\n" +
            "            \"MRBZ\": \"Y\",\n" +
            "            \"xydjxx\": [],\n" +
            "            \"nsrlx\": {\n" +
            "                \"QYLXDM\": \"10\"\n" +
            "            },\n" +
            "            \"NSRSBH\": \"91330109MA2GLE0WXT\"\n" +
            "        }\n" +
            "    }\n" +
            "}";

    @Test
    public void assemblePoint() {
        new Case68_4().assemblePoint();
    }

    @Test
    public void getPzxh(){
        JSONObject jsonObject = JSON.parseObject(s);
        JSONObject jsonObject1 = jsonObject.getJSONObject("resultObj");
        JSONArray array = jsonObject1.getJSONArray("sbxmlist");
        for (int i = 0; i < array.size(); i++){
            JSONObject jsonObject2 = array.getJSONObject(i);
            String sbxmdm = jsonObject2.getString("sbxmdm");
            if ("fjsf".equals(sbxmdm)){
                String pzxh = jsonObject2.getString("pzxh");
                System.out.println(pzxh);
            }
        }

    }
}